name: CI/CD Pipeline for Mini Store API

on:
  push:
    branches: [ main ] # Kích hoạt pipeline mỗi khi có code mới push vào nhánh main

jobs:
  build-and-deploy:
    runs-on: self-hosted # 👈 Ra lệnh cho GitHub điều phối công việc xuống máy WSL dưới nhà anh
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Tải code mới nhất vừa push về thư mục tạm của runner

      - name: Execute Local Deployment
        run: |
          cd ~/projects/mini_store_api
          docker compose pull
          docker compose up -d --remove-orphans
          docker compose exec -T web bin/rails db:migrate
